/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ece8e0",
        "on-surface": "#1c1c17",
        "surface": "#fdf9f1",
        "surface-variant": "#e6e2da",
        "on-primary-fixed": "#00164e",
        "on-secondary": "#ffffff",
        "outline": "#757682",
        "outline-variant": "#c5c5d2",
        "on-primary-container": "#b5c4ff",
        "surface-container-highest": "#e6e2da",
        "on-secondary-container": "#785a19",
        "inverse-surface": "#31302b",
        "primary": "#1d367f",
        "inverse-primary": "#b6c4ff",
        "secondary-fixed-dim": "#e8c176",
        "surface-container": "#f1ede6",
        "on-tertiary-fixed-variant": "#504535",
        "surface-bright": "#fdf9f1",
        "background": "#fdf9f1",
        "primary-container": "#374e98",
        "tertiary": "#453a2b",
        "on-background": "#1c1c17",
        "primary-fixed": "#dce1ff",
        "surface-tint": "#445aa5",
        "tertiary-container": "#5d5141",
        "on-primary-fixed-variant": "#2a428b",
        "tertiary-fixed-dim": "#d5c4af",
        "secondary-container": "#fdd487",
        "on-secondary-fixed": "#261900",
        "on-tertiary-container": "#d5c4b0",
        "inverse-on-surface": "#f4f0e8",
        "error": "#ba1a1a",
        "surface-dim": "#dddad2",
        "on-surface-variant": "#444651",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffdea4",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-low": "#f7f3eb",
        "on-tertiary-fixed": "#231a0d",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#f2e0ca",
        "on-secondary-fixed-variant": "#5d4200",
        "secondary": "#775a19",
        "primary-fixed-dim": "#b6c4ff"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "unit": "8px",
        "section-gap": "120px",
        "container-max": "1440px",
        "gutter": "32px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "label-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Cormorant Garamond", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Cormorant Garamond", "serif"],
        "headline-sm": ["Cormorant Garamond", "serif"],
        "headline-md": ["Cormorant Garamond", "serif"],
        "body-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "300" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
